### ISSUE TITLE
Freeze layout when assigning Exclusivity Groups

### ISSUE THREAD

**Issue by danjoyce-origin** [JohnHasthorpe/QuickCapture-Holistic#1]
When I was attempting to assign buttons to an exclusivity group I was able to move a button from one group to another.

**Comment by danjoyce-origin** [comment]
When on Project description page in iOS, if a change is made to the project in the designer (i.e. changing project description page), the Project update available message is displayed.  I press UPDATE and the progress circle gets 75% of the way then disappears and the UPDATE message reappears.  After about 5 seconds the message disappears and the updated content is shown.

**Comment by JohnHasthorpe** [comment]
Internal issue raised: https://devtopia.esri.com/Melbourne/QuickCapture-Web/issues/494
