### ISSUE TITLE
Camera not enabled on new buttons in app

### ISSUE THREAD

**Issue by J8L** [JohnHasthorpe/QuickCapture-Holistic#10]
I don't think i am doing anything wrong... I created a project with multiple buttons all pointing the the same hosted feature. I added new buttons rather than copying the first button. In the web designer it all looks good, however in the app the camera icon is missing from the buttons and photos are not enabled. All the buttons have the same configuration. I wouldn't have thought it would be a version issue. 

web designer:
https://www.arcgis.com/apps/quickcapture/project/bec43f0a0bf94df69913de6731aaa2ee/design

app version:
Windows v1.2.84
iOS current version on the Apple Store
Android v1.0.286

![QuickCaptue_Camera](https://user-images.githubusercontent.com/42594789/65214425-40c0eb00-daed-11e9-8d79-db3794b403c4.png)

**Comment by JohnHasthorpe** [comment]
@J8L - Can you press and hold the about button in the app for 5 seconds. This should reveal a sync button. Press the button to reset the database. The download the project again and re-test.

**Comment by J8L** [comment]
@JohnHasthorpe we had someone up in a plane this morning collecting data with QuickCapture so i just copied the buttons and that worked. I created a new project just now with the same parameters to test and had no issue. Typical!! We have a few more projects to create over the next few weeks so if i see this issue again I will test the sync button. Thanks for the tip!

**Comment by JohnHasthorpe** [comment]
No further action required on this. Closing
