### ISSUE TITLE
Drop-down menu off the page

### ISSUE THREAD

**Issue by J8L** [JohnHasthorpe/QuickCapture-Holistic#2]
When you select a drop-down menu at the bottom of the page, it runs off the screen. It may be good to have the drop-down menu run up when you are in the lower 1/3 of the screen.

Google Chrome Version 76.0.3809.132 (Official Build) (64-bit)

![Drop-Down](https://user-images.githubusercontent.com/42594789/64396715-dc8c3900-d0a1-11e9-8c63-bfd1d8a16564.png)

**Comment by JohnHasthorpe** [comment]
Issue created: https://devtopia.esri.com/Melbourne/QuickCapture-Web/issues/477
