### ISSUE TITLE
GPS Receiver Name internal or external

### ISSUE THREAD

**Issue by J8L** [JohnHasthorpe/QuickCapture-Holistic#3]
It would be good to select 'Receiver Name' as a generic field regardless of internal or external GPS device and allow behind-the-scenes smarts to identify if the GPS is internal or external. This way it doesn't matter if an external GPS is connected or not, you will always get a value returned.
![GPS_Receiver_Name](https://user-images.githubusercontent.com/42594789/64396888-879cf280-d0a2-11e9-944e-4d7d0aadaf8a.png)

**Comment by JohnHasthorpe** [comment]
Issue created for this: https://devtopia.esri.com/Melbourne/QuickCapture/issues/580
