### ISSUE TITLE
Update message persisting after tapping

### ISSUE THREAD

**Issue by danjoyce-origin** [JohnHasthorpe/QuickCapture-Holistic#5]
When on Project description page in iOS, if a change is made to the project in the designer (i.e. changing project description page), the Project update available message is displayed. I press UPDATE and the progress circle gets 75% of the way then disappears and the UPDATE message reappears. After about 5 seconds the message disappears and the updated content is shown.

**Comment by JohnHasthorpe** [comment]
Fixed in 1.2 Closing
