### ISSUE TITLE
App - open on-screen keyboard by default when user input is required

### ISSUE THREAD

**Issue by J8L** [JohnHasthorpe/QuickCapture-Holistic#9]
When a project is opened with a required **userInput field**, it would be good to have **input window active** and the **on-screen keyboard launch** automatically. Currently you need to select the input window before the keyboard opens. This behavior is the same on the Windows and iOS versions, and i assume Android.

![Image-1](https://user-images.githubusercontent.com/42594789/64498001-95968180-d2f5-11e9-8216-b5c49375fdad.jpg)

**Comment by JohnHasthorpe** [comment]
Issue created: https://devtopia.esri.com/Melbourne/QuickCapture/issues/374
